### PR TITLE
Change typo in matrix docs

### PR DESCRIPTION
**Pull request by iamdustan**
Change docs text `identity` to the method name `identify`

### CODE REVIEW

**Comment by iamdustan** [comment]
Fixed according to https://github.com/uxebu/bonsai-docs/issues/35#issuecomment-10868193

**Comment by davidaurelio** [comment]
Thanks, that was super quick. Wanted to do it to prevent double work for you. To slow …

**Comment by iamdustan** [comment]
Ha. Already had it all open on the side. I do a lot of `git grep` on the bonsai source these days :)

**Comment by davidaurelio** [comment]
:)

**Pull request merged**
