### PR TITLE
KeyframeAnimation cleanup as per #51

### PR DESCRIPTION
**Pull request by padolsey**
See https://github.com/uxebu/bonsai/issues/51

### CODE REVIEW

**Comment by klipstein** [comment]
@padolsey are other projects affected by that change? i just remember that we once had to change it in `transwf`.

**Comment by padolsey** [comment]
I've done a search for `setSubject` in transwf and can't find anything. I don't think transwf uses the KeyframeAnimation class either.

**Comment by basecode** [comment]
Looks good! Could you pls add an entry to the change logs?

**Comment by basecode** [comment]
Not sure about the tests. I think we already have tests that cover `addSubject`. Can't we just remove the tests regarding `setSubject`?

**Comment by padolsey** [comment]
No new tests were added. I changed old tests that were using the setSubject(s) methods. Those specific tests were testing other KeyframeAnimation behaviour (so we should keep them).

**Pull request merged**
