### PR TITLE
Implement getAbsoluteBoundingBox and getAbsoluteMatrix

### PR DESCRIPTION
**Pull request by padolsey**
Discussion point: Is it better to have a `getBoundingBoxRelativeTo`?

### CODE REVIEW

**Comment by davidaurelio** [comment]
boundingBoxRelativeTo is: find common ancestor, compute bounding boxes relative to that, apply difference. Not sure whether we really need that

I think `getParentBoundingBox` / `getBoundingBoxParent` is really needed.

**Comment by davidaurelio** [comment]
+1 for `getAbsoluteMatrix()`. That’s cool to have!

**Comment by iamdustan** [comment]
Could I propose `getAbsoluteTransformOrigin` as well? :)

**Comment by basecode** [comment]
Related: #126

**Comment by basecode** [comment]
What I can see is that 
- our current implementation of `getBoundingBox` actually returns the local offset (#126 explains terminology)
- `getAbsoluteBoundingBox` returns the userspace resp. global offset. Exactly what SVG's `getBBox` is known for.
- `getParentBoundingBox` (proposed by @davidaurelio) would be neat to have.

I propose the following:
- rename `getBoundingBox` to `getLocalBBox(aMatrix)`
- rename `getAbsoluteBoundingBox` to `getBBox()` or `getAbsoluteBBox`
- rename `getParentBoundingBox` to `getParentBBox()`

`getBBox` is an equivalent to `getLocalBBox(this.getAbsoluteMatrix())`
`getParentBoundingBox` is equivalent to `getLocalBBox(this.attr('matrix'))`

**Pull request merged**
