### PR TITLE
Just trigger on click for touchstart+end

### PR DESCRIPTION
**Pull request by wolframkriesing**
this branch contains the missing test for the fix submited in https://github.com/uxebu/bonsai/commit/4ac85d2b805e107908c866250179f69b66710a2e and examples that show the fixed behavior

### CODE REVIEW

**Comment by davidaurelio** [comment]
I guess from reading the code, that the supplied test case might not fail with the old code. I will take the time to change it later.

**Comment by wolframkriesing** [comment]
I tried  it with the old code and it failed
Am 09.11.2012 11:15 schrieb "David Aurelio" notifications@github.com:

**Comment by wolframkriesing** [comment]
But please doubke check

**Comment by davidaurelio** [comment]
Good that I wrote “guess” and “might” ;-) just read through it, will try it out later.

**Pull request merged**
