### PR TITLE
Implemented rudimentary charCode to be returned by keydown event.

### PR DESCRIPTION
**Pull request by wolframkriesing**
Added a basic implementation of charCode to return for keydown events, as long as they are broken in DOM.

### CODE REVIEW

**Comment by basecode** [comment]
Looks fine. Two questions:
- Does it make sense to expose both values? charcode and keycode
- What about `which`? http://stackoverflow.com/a/1445228

**Comment by wolframkriesing** [comment]
i dont care if it is called `which` or `keyCode` in the end, i think `keyCode` is more explicit

**Comment by basecode** [comment]
The wording wasn't subject of my question. I asked why we expose `charcode` and `keycode` and why we ignore `event.which` (see link).

**Comment by wolframkriesing** [comment]
tbh the article confuses me, which is the same as keycode in some cases, in that case i think `charCode` and `keyCode` are the best choices, they clearly state that they are different and what the mean (maybe I am a bit flash biased). but i see no value in `which`, and esp. that it could mean a lot and nothing

**Comment by davidaurelio** [comment]
Closed in favor of #201

**Pull request closed without merging**
