### PR TITLE
Change drag/multi:drag ui events to bubblable

### PR DESCRIPTION
**Pull request by iamdustan**
See #184

Tested in:
- Chrome 25 beta
- Opera 12.02
- Firefox 19 beta
- Safari 5.1

### CODE REVIEW

**Comment by davidaurelio** [comment]
Sorry nobody took care of this yet. 

@basecode: is more discussion needed? I’m ok with this change.

**Comment by basecode** [comment]
Looks fine! Thanks, @iamdustan.

**Comment by iamdustan** [comment]
:thumbsup: thanks @davidaurelio. I didn’t push the issue to hard since your tree traversal change hasn’t been reviewed at all either. I’m sure you guys are plenty busy with Pixelplant.

**Comment by davidaurelio** [comment]
That’s true. I’d like to give some more love to bonsai

**Pull request merged**
